apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-limited-access
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-limited-access
rules:
- apiGroups:
  - ""
  - "apps"
  - "autoscaling"
  resources:
  - "*"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "delete"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-limited-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-limited-access
subjects:
- kind: ServiceAccount
  name: namespace-limited-access
  namespace: default