apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-limited-read
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-limited-read
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "endpoints"
  - "pods"
  - "pv"
  verbs:
  - "get"
  - "list"
  - "watch"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-limited-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-limited-read
subjects:
- kind: ServiceAccount
  name: namespace-limited-read
  namespace: default